"""stage3_explanations

Revision ID: 082f4bce7d81
Revises: 49f6179bb7ee
Create Date: 2026-09-24 02:32:31.291034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '082f4bce7d81'
down_revision: Union[str, Sequence[str], None] = '49f6179bb7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_explanations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('packet_hash', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.String(length=600), nullable=False),
    sa.Column('probable_causes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lesson', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('training_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('grounding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fallback_reason', sa.String(length=32), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'packet_hash', name='uq_incident_explanations_incident_packet')
    )
    op.create_index('ix_incident_explanations_incident_created', 'incident_explanations', ['incident_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_explanations_incident_created', table_name='incident_explanations')
    op.drop_table('incident_explanations')
    # ### end Alembic commands ###
