"""initial_batch3a

Revision ID: 2ab54d562062
Revises: 
Create Date: 2026-09-23 22:36:06.778255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ab54d562062'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('machine_type', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('first_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_machine_key', 'alerts', ['machine_id', 'key'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_engine', sa.String(length=64), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('frame_seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'frame_seq', 'type', name='uq_events_machine_seq_type')
    )
    op.create_index('ix_events_machine_ts', 'events', ['machine_id', 'ts'], unique=False)
    op.create_table('machine_state_log',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('frame_seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('ts', 'machine_id')
    )
    op.create_index('ix_state_log_machine_ts', 'machine_state_log', ['machine_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_state_log_machine_ts', table_name='machine_state_log')
    op.drop_table('machine_state_log')
    op.drop_index('ix_events_machine_ts', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_alerts_machine_key', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('machines')
    # ### end Alembic commands ###
