"""stage3_incidents

Revision ID: 49f6179bb7ee
Revises: d6114ec31a5b
Create Date: 2026-09-24 01:45:16.037043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f6179bb7ee'
down_revision: Union[str, Sequence[str], None] = 'd6114ec31a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('close_note', sa.String(length=500), nullable=True),
    sa.Column('trigger_event_id', sa.UUID(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('risk_level_at_open', sa.String(length=16), nullable=True),
    sa.Column('explanation_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['trigger_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_machine_status_last_event', 'incidents', ['machine_id', 'status', 'last_event_at'], unique=False)
    op.create_index('ix_incidents_site_opened', 'incidents', ['site_id', 'opened_at'], unique=False)
    op.create_table('incident_events',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'event_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('incident_timeline',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('entry_key', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('first_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('representative_event_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'entry_key', 'first_ts', name='uq_incident_timeline_key_first_ts')
    )
    op.create_index('ix_incident_timeline_incident_order', 'incident_timeline', ['incident_id', 'first_ts', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_timeline_incident_order', table_name='incident_timeline')
    op.drop_table('incident_timeline')
    op.drop_table('incident_events')
    op.drop_index('ix_incidents_site_opened', table_name='incidents')
    op.drop_index('ix_incidents_machine_status_last_event', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
