"""stage4_lessons

Revision ID: a504e0bd6bc3
Revises: 082f4bce7d81
Create Date: 2026-09-24 08:30:00.952476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a504e0bd6bc3'
down_revision: Union[str, Sequence[str], None] = '082f4bce7d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('short_tip', sa.String(length=200), nullable=False),
    sa.Column('explanation', sa.String(length=800), nullable=False),
    sa.Column('knowledge_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fallback_reason', sa.String(length=32), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id')
    )
    op.create_index('ix_lessons_operator_delivered', 'lessons', ['operator_id', 'delivered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lessons_operator_delivered', table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
