"""stage3_warm_path

Revision ID: d6114ec31a5b
Revises: f8233ae3dc68
Create Date: 2026-09-24 01:23:00.960130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6114ec31a5b'
down_revision: Union[str, Sequence[str], None] = 'f8233ae3dc68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('window_aggregates',
    sa.Column('window_id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('operator_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame_count', sa.Integer(), nullable=False),
    sa.Column('first_seq', sa.Integer(), nullable=True),
    sa.Column('last_seq', sa.Integer(), nullable=True),
    sa.Column('late_frames', sa.Integer(), nullable=False),
    sa.Column('fuel_per_cycle', sa.Float(), nullable=True),
    sa.Column('rpm_mean', sa.Float(), nullable=True),
    sa.Column('rpm_std', sa.Float(), nullable=True),
    sa.Column('hyd_p95', sa.Float(), nullable=True),
    sa.Column('idle_ratio', sa.Float(), nullable=True),
    sa.Column('cycle_count', sa.Integer(), nullable=True),
    sa.Column('cycle_time_mean', sa.Float(), nullable=True),
    sa.Column('cycle_time_cv', sa.Float(), nullable=True),
    sa.Column('temp_slope', sa.Float(), nullable=True),
    sa.Column('working_ratio', sa.Float(), nullable=True),
    sa.Column('truck_present_ratio', sa.Float(), nullable=True),
    sa.Column('hauler_queue_mean', sa.Float(), nullable=True),
    sa.Column('fuel_l_total', sa.Float(), nullable=True),
    sa.Column('alerts_count', sa.Integer(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idle_attribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('anomaly', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deviation_raw_flag', sa.Boolean(), nullable=False),
    sa.Column('deviation_consecutive', sa.Integer(), nullable=False),
    sa.Column('last_eta_slip_band', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('window_id')
    )
    op.create_index('ix_window_aggregates_machine_start', 'window_aggregates', ['machine_id', 'window_start'], unique=False)
    op.create_table('eta_estimates',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=False), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=32), nullable=False),
    sa.Column('window_id', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'window_id', 'kind', name='uq_eta_task_window_kind')
    )
    op.create_index('ix_eta_estimates_task_ts', 'eta_estimates', ['task_id', 'ts'], unique=False)
    op.create_index('uq_eta_baseline_per_task', 'eta_estimates', ['task_id'], unique=True, postgresql_where=sa.text("kind = 'BASELINE'"))
    op.add_column('tasks', sa.Column('task_type', sa.String(length=32), nullable=True))
    op.add_column('tasks', sa.Column('target_cycles', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('skill_level', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skill_level')
    op.drop_column('tasks', 'planned_start')
    op.drop_column('tasks', 'target_cycles')
    op.drop_column('tasks', 'task_type')
    op.drop_index('uq_eta_baseline_per_task', table_name='eta_estimates', postgresql_where=sa.text("kind = 'BASELINE'"))
    op.drop_index('ix_eta_estimates_task_ts', table_name='eta_estimates')
    op.drop_table('eta_estimates')
    op.drop_index('ix_window_aggregates_machine_start', table_name='window_aggregates')
    op.drop_table('window_aggregates')
    # ### end Alembic commands ###
